name: CI

on:
    pull_request:
        branches: [main]

jobs:
    dbt-build:
        runs-on: ubuntu-latest

        env:
            DBT_GCP_PROJECT_ID: ${{ secrets.DBT_GCP_PROJECT_ID }}

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: Install dbt
              run: |
                  pip install dbt-core dbt-bigquery

            - name: Install dbt dependencies
              run: dbt deps

            - name: Write service account JSON to file
              run: |
                  echo '${{ secrets.DBT_PROD_KEYFILE }}' > /tmp/service_account.json

            - name: Set up dbt profile
              run: |
                  mkdir -p ~/.dbt
                  cat <<EOF > ~/.dbt/profiles.yml
                  dbt_core_bigquery:
                    target: dev
                    outputs:
                      dev:
                        type: bigquery
                        method: service-account
                        project: ${{ secrets.DBT_GCP_PROJECT_ID }}
                        dataset: dbt_prod
                        location: US
                        threads: 4
                        job_execution_timeout_seconds: 300
                        job_retries: 1
                        priority: interactive
                        keyfile: /tmp/service_account.json
                  EOF
                  chmod 600 ~/.dbt/profiles.yml

            - name: Run dbt build
              run: dbt build --target dev
