name: CI

on:
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        env:
            GCP_PROJECT_ID: "{{ env_var('GCP_PROJECT_ID') }}"
            DBT_GCP_PROJECT_ID: ${{ secrets.DBT_GCP_PROJECT_ID }}
            DBT_PROFILES_DIR: .

        steps:
            # Step 1: Checkout the repo
            - name: Checkout repo
              uses: actions/checkout@v3

            # Step 2: Set up the Python environment
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            # Step 3: Upgrade pip and setuptools

            - name: Upgrade pip and setuptools
              run: |
                  python -m pip install --upgrade pip setuptools wheel

            # Step 4: Set up virtual environment and install dependencies
            - name: Set up Virtual Environment
              run: |
                  python -m venv dbt_bigquery_venv
                  source dbt_bigquery_venv/bin/activate
                  pip install dbt-core dbt-bigquery

            # Step 5: Create gcp-key.json and profiles.yml
            - name: Create GCP Key and profiles.yml
              run: |
                  echo '${{ secrets.DBT_PROD_KEYFILE }}' > /tmp/service_account.json

                  cat <<EOF > /home/runner/.dbt/profiles.yml
                  dbt_core_bigquery:
                  outputs:
                      dev:
                      dataset: dbt_prod
                      job_execution_timeout_seconds: 300
                      job_retries: 1
                      keyfile: /tmp/service_account.json
                      location: US
                      method: service-account
                      priority: interactive
                      project: dbt-core-bq-learn
                      threads: 1
                      type: bigquery

                  target: dev
                  EOF

            - name: Install dbt dependencies
              run: dbt deps

            - name: Run dbt Tests
              run: |
                  source dbt_bigquery_venv/bin/activate
                  dbt test --profiles-dir /home/runner/.dbt --target dev
