name: CI

on:
    pull_request:
        branches: [main]

jobs:
    dbt-build:
        runs-on: ubuntu-latest

        env:
            DBT_PROD_KEYFILE: ${{ secrets.DBT_PROD_KEYFILE }}

        steps:
            - uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: |
                  pip install dbt-core dbt-bigquery

            - name: Install dbt dependencies
              run: dbt deps

            - name: Set up dbt profile
              run: |
                  mkdir -p ~/.dbt
                  echo -e "${DBT_PROFILES_YML}" > ~/.dbt/profiles.yml
              env:
                  DBT_PROFILES_YML: ${{ secrets.DBT_PROFILES_YML }}

            - name: Set up prod keyfile
              run: |
                  echo "${{ secrets.DBT_PROD_KEYFILE }}" | base64 -d > /tmp/service-account.json
              env:
                  DBT_PROD_KEYFILE: /tmp/service-account.json

            - name: Run dbt commands
              run: dbt debug --target prod
                  dbt build --target prod
